### ISSUE TITLE
calculate gpu count error strconv.Atoi: parsing "": invalid syntax

### ISSUE THREAD

**Issue by TaylorHere** [virtual-kubelet/alibabacloud-eci#6]
```
apiVersion: v1
kind: Pod
metadata:
  name: tensorflow
  annotations:
    k8s.aliyun.com/eci-gpu-type : "T4"
spec:
  containers:
  - image: registry-vpc.cn-hangzhou.aliyuncs.com/ack-serverless/tensorflow
    name: tensorflow
    command:
    - "sh"
    - "-c"
    - "python models/tutorials/image/imagenet/classify_image.py"
    resources:
      limits:
        nvidia.com/gpu: "1"
  - image: some-other-container 
    name: no-gpu-limits
```
if apply this pod into the cluster, will cause 
```
  Warning  ParamsAdapterFailed  26s   virtual-kubelet-0/pod-controller  calculate gpu count error strconv.Atoi: parsing "": invalid syntax
```
